<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Enter your query_vfb-23</name>
   <tag></tag>
   <elementGuidId>ac8997f3-c08e-4532-b8f0-3920be8c5b76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='vfb-23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>65750e1c-6fb7-4280-8938-1e2b6d1226f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-23</value>
      <webElementGuid>23e3360c-d75a-447b-bfeb-cae54e2c3652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-23</value>
      <webElementGuid>d805f072-fe32-46fa-9410-e21fc186c707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-textarea  vfb-medium  </value>
      <webElementGuid>5f102e09-b616-4b81-aba4-510b1e5fedf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-23&quot;)</value>
      <webElementGuid>8f04f7f1-cc25-49ed-b71e-6faf115e74a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='vfb-23']</value>
      <webElementGuid>cf7c34c1-f05f-4232-b489-e0f65c42cedb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-23']/div/textarea</value>
      <webElementGuid>6b42c78b-67b6-42e5-8e83-a4b57e4b0aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>0d7384e0-4861-45f5-a7ca-8c0c55357657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'vfb-23' and @id = 'vfb-23']</value>
      <webElementGuid>09d6e626-0023-4bc2-91ea-35d58ad9c02e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
